---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment to ${ENV_NAME} environment"
  test-tasks: &test-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Testing on ${ENV_NAME} environment"

pipelines:
  node-microservice:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/mtararujs/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Building application"
      - deploy-dev:
          environment_variables:
              ENV_NAME: dev
          jobs:
            build:
              tasks: *deploy-tasks
      - test-dev:
          jobs:
            build:
              tasks: *test-tasks
      - deploy-int:
          environment_variables:
              ENV_NAME: int
          jobs:
            build:
              tasks: *deploy-tasks
      - test-int:
          jobs:
            build:
              tasks: *test-tasks
      - deploy-prd:
          environment_variables:
              ENV_NAME: prd
          jobs:
            build:
              tasks: *deploy-tasks
      - test-prd:
          jobs:
            build:
              tasks: *test-tasks
