---
format_version: 10
pipelines:
  node-microservice:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/mtararujs/ci_course.git
        brach: main
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - -c
                    - echo "Building application"
